### ISSUE TITLE
【デート】整体・マッサージ事前調査資料

### ISSUE THREAD

**Issue by fruitsnoodle** [fruitsnoodle/couple#24]
@kubosho 確認をお願いします
## リフレッシュサロン和

http://www.nagomi-tiad.com/
- ペア個室あり
- 最寄り駅：神田
- オンライン予約可
- 参考価額：ペア60分で4800円/一人
- 秋葉原に近い
## リックスケア凛

http://relaxcare-rin.co.jp/
- 最寄り駅：秋葉原
- ペア個室なし
- 参考価額：60分で6000円
- 秋葉原に近い
## ペルラスパ

http://www.perla-spa.com/index.html
- 完全個室あり
- 最寄り駅：六本木
- 参考価額：ボディケア60分6800円　シャワー10分1050円、20分2100円
- おしゃれ
## ミスとモック

http://www.mistmokh.co.jp/
- ペア個室あり
- 最寄り駅：池袋
- 参考価額：リンパデトックス60分コースお二人様で￥10,584(税込)
- オンライン予約可
- メイド喫茶の帰りにいい
## シャレーメン

http://beauty.hotpepper.jp/kr/slnH000209633/?cstt=18
- ペア貸切可
- 最寄り駅：池袋
- 参考価額：ペア貸切1時間2人で8400円
- メイド喫茶の帰りにいい
## 京都ほぐし整体はんなり

http://www.hannari-asia.com/akasaka/index.html
- 完全個室あり
- 最寄り駅：赤坂
- 参考価額：ほぐし整体60分5500円
- 京風が気に入り

**Comment by kubosho** [comment]
ミストモック予約した。6/8 の 16:00 から
